[package]
name = "lee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
serde_json = "1.0.114"
reqwest = "0.11.27"
tokio = "1.36.0"
shlex = "1.3.0"
futures = "0.3.30"
